/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;

import Model.Player;
import java.io.File;
import javax.sound.sampled.*;

/**
 *
 * this component contains child components
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public static Player pl;
    private static Clip clip;

    public Main() {
        initComponents();
        // set up a login dialog
        loginDg.setSize(loginDg.getPreferredSize());
        loginDg.setLocationRelativeTo(null);
        loginDg.setVisible(true);
        // set up a sign dalog        
        signDg.setSize(signDg.getPreferredSize());
        signDg.setLocationRelativeTo(null);
        PlayMusic("../Chess_Engine/src/main/java/Music/bg2.wav");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginDg = new javax.swing.JDialog();
        passTxt = new javax.swing.JPasswordField();
        usrTxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        signBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signDg = new javax.swing.JDialog();
        usrSTxt = new javax.swing.JTextField();
        passSTxt = new javax.swing.JPasswordField();
        rpassSTxt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signSBtn = new javax.swing.JButton();
        loginSBtn = new javax.swing.JButton();

        loginDg.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        loginDg.setTitle("Login");
        loginDg.setIconImage(null);
        loginDg.setResizable(false);
        loginDg.setSize(new java.awt.Dimension(401, 196));

        loginBtn.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        loginBtn.setText("Login");

        signBtn.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        signBtn.setText("Sign Up");
        signBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel2.setText("Password");

        javax.swing.GroupLayout loginDgLayout = new javax.swing.GroupLayout(loginDg.getContentPane());
        loginDg.getContentPane().setLayout(loginDgLayout);
        loginDgLayout.setHorizontalGroup(
            loginDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDgLayout.createSequentialGroup()
                .addGroup(loginDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginDgLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(loginDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passTxt)
                            .addComponent(usrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginDgLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(signBtn)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        loginDgLayout.setVerticalGroup(
            loginDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDgLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(loginDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(loginDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        signDg.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        signDg.setTitle("Sign Up");
        signDg.setPreferredSize(new java.awt.Dimension(401, 250));
        signDg.setResizable(false);
        signDg.setSize(new java.awt.Dimension(401, 250));

        jLabel3.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel5.setText("RPassword");

        signSBtn.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        signSBtn.setText("Sign");
        signSBtn.setToolTipText("");

        loginSBtn.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        loginSBtn.setText("Sign In");
        loginSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signDgLayout = new javax.swing.GroupLayout(signDg.getContentPane());
        signDg.getContentPane().setLayout(signDgLayout);
        signDgLayout.setHorizontalGroup(
            signDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signDgLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(signDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passSTxt)
                    .addComponent(usrSTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rpassSTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(signDgLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(signSBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginSBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signDgLayout.setVerticalGroup(
            signDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signDgLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(signDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usrSTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passSTxt)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rpassSTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(signDgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signSBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginSBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        usrSTxt.getAccessibleContext().setAccessibleName("");
        usrSTxt.getAccessibleContext().setAccessibleDescription("");

        signDg.getAccessibleContext().setAccessibleParent(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess Game");
        setLocation(new java.awt.Point(400, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // move to sign dialog
    private void signBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signBtnActionPerformed
        loginDg.dispose();
        usrTxt.setText("");
        passTxt.setText("");
        signDg.setVisible(true);
    }//GEN-LAST:event_signBtnActionPerformed

    private void loginSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSBtnActionPerformed
        usrSTxt.setText("");
        passSTxt.setText("");
        rpassSTxt.setText("");
        loginDg.setVisible(true);
        signDg.dispose();
    }//GEN-LAST:event_loginSBtnActionPerformed

    // update after change
    public void UpdateUI() {
        if (pl != null) {
            if ("on".equals(pl.getSound())) {

                setVolume();
                clip.start();
            } else if ("off".equals(pl.getSound())) {
                if (clip != null) {
                    clip.stop();
                }
            }
        }
    }

    //set volume
    private void setVolume() {
        if (pl != null) //set volume
        {
            FloatControl gainControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
            double gain = (float) pl.getSoundVl() / 100; // number between 0 and 1 (loudest)
            float dB = (float) (Math.log(gain) / Math.log(10.0) * 20.0);
            gainControl.setValue(dB);

        }
    }

    // play music
    public static void PlayMusic(String url) {

        AudioInputStream sound;
        try {
            File file = new File(url);
            sound = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(sound);
            // loop bg music
            clip.loop(Clip.LOOP_CONTINUOUSLY);
            clip.stop();

        } catch (Exception e) {
        }

    }

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                var main = new Main();

            }
        });

    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JButton loginBtn;
    public javax.swing.JDialog loginDg;
    public javax.swing.JButton loginSBtn;
    public javax.swing.JPasswordField passSTxt;
    public javax.swing.JPasswordField passTxt;
    public javax.swing.JPasswordField rpassSTxt;
    public javax.swing.JButton signBtn;
    public javax.swing.JDialog signDg;
    public javax.swing.JButton signSBtn;
    public javax.swing.JTextField usrSTxt;
    public javax.swing.JTextField usrTxt;
    // End of variables declaration//GEN-END:variables
}
