/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Game;

import Model.Player;

/**
 *
 * @author Asus
 */
public class Setting extends javax.swing.JPanel {

    /**
     * Creates new form Setting
     */
    private String theme;
    private String sound;
    private int soundVl;

    public Setting() {
        initComponents();
        buttonGroup1.add(hellRBtn);
        buttonGroup1.add(defaultRBtn);
        buttonGroup1.add(skyRBtn);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        soundTBtn = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        soundSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        defaultRBtn = new javax.swing.JRadioButton();
        skyRBtn = new javax.swing.JRadioButton();
        hellRBtn = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        soundTBtn.setText("jToggleButton1");

        jLabel2.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel2.setText("Sound volume");

        jLabel3.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel3.setText("Sound");

        soundSlider.setValue(70);

        jLabel4.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        jLabel4.setText("Board Theme");

        defaultRBtn.setText("Fall");

        skyRBtn.setText("Sky");

        hellRBtn.setText("Hell");

        saveBtn.setBackground(new java.awt.Color(209, 209, 209));
        saveBtn.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(60, 46, 3));
        saveBtn.setText("Save");
        saveBtn.setToolTipText("");
        saveBtn.setFocusPainted(false);

        backBtn.setBackground(new java.awt.Color(209, 209, 209));
        backBtn.setFont(new java.awt.Font("STCaiyun", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(60, 46, 3));
        backBtn.setText("Back");
        backBtn.setToolTipText("");
        backBtn.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soundTBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(defaultRBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(skyRBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hellRBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(soundSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soundTBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(soundSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultRBtn)
                    .addComponent(skyRBtn)
                    .addComponent(hellRBtn))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // update setting properties

    public void Update() {
        this.soundVl = soundSlider.getValue();
        if (soundTBtn.isSelected()) {
            this.sound = "on";
        } else {
            this.sound = "off";
        }
        // compare radio btn
        if (defaultRBtn.isSelected()) {
            this.theme = "fall";
        } else if (skyRBtn.isSelected()) {
            this.theme = "sky";
        } else if (hellRBtn.isSelected()) {
            this.theme = "hell";
        }

        System.out.println(soundVl + " " + theme + " " + sound + ", update setting no player");
    }

    public Player getPlayerSt() {
        return new Player(sound, soundVl, theme);
    }
// Update setting through player

    public void Update(Player s) {
        System.out.println(s);
        if ("on".equals(s.getSound())) {
            soundTBtn.setSelected(true);
            soundTBtn.setText("On");
        } else if ("off".equals(s.getSound())) {
            soundTBtn.setSelected(false);
            soundTBtn.setText("Off");
        }
        soundSlider.setValue(s.getSoundVl());
        switch (s.getTheme()) {
            case "fall" ->
                defaultRBtn.setSelected(true);
            case "sky" ->
                skyRBtn.setSelected(true);
            case "hell" ->
                hellRBtn.setSelected(true);
            default -> {
            }
        }
        Update();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backBtn;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JRadioButton defaultRBtn;
    public javax.swing.JRadioButton hellRBtn;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JButton saveBtn;
    public javax.swing.JRadioButton skyRBtn;
    public javax.swing.JSlider soundSlider;
    public javax.swing.JToggleButton soundTBtn;
    // End of variables declaration//GEN-END:variables
}
